### ISSUE TITLE
Worked great until a day ago

### ISSUE THREAD

**Issue by bugrelgit** [aisegmentcn/aisegment_obs_plugin#14]
I absolutely love this plugin it worked great until yesterday now it has stopped working, is it because of new AI laws perhaps

**Comment by aisegmentcn** [comment]
Please update the obs.lic file:
https://github.com/aisegmentcn/aisegment_obs_plugin/blob/main/data/obs.lic
We have update it three days ago.

**Comment by bugrelgit** [comment]
Thank you Stephen for the update, This is without a doubt an absolutely fantastic plugin

**Comment by bugrelgit** [comment]
Thank you very much for your help
